imports:
    - { resource: config.yml }

hautelook_alice:
    db_drivers:
        orm: ~
    locale: "nl_NL"
    seed: 1
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
