odp_huurders_index:
    path: odp_huurders

odp_verhuurders_index:
    path: odp_verhuurders

odp_huurverzoeken_index:
    path: odp_huurverzoeken

odp_huuraanbiedingen_index:
    path: odp_huuraanbiedingen

odp_huurovereenkomsten_index:
    path: odp_huurovereenkomsten