services:
    odp.data_fixtures.faker_provider:
        class: OdpBundle\DataFixtures\OdpFakerProvider
        tags:
            - { name: hautelook_alice.faker.provider }

    odp.dao.coordinator:
        parent: app.dao.abstract
        class: OdpBundle\Service\CoordinatorDao

    odp.dao.document:
        class: OdpBundle\Service\DocumentDao
        arguments:
            - '@doctrine.orm.entity_manager'

    odp.dao.huurderafsluiting:
        parent: app.dao.abstract
        class: OdpBundle\Service\HuurderafsluitingDao

    odp.dao.verhuurderafsluiting:
        parent: app.dao.abstract
        class: OdpBundle\Service\VerhuurderafsluitingDao

    odp.dao.woningbouwcorporatie:
        parent: app.dao.abstract
        class: OdpBundle\Service\WoningbouwcorporatieDao
